---

# 销毁集群


- hosts: via
  tags:
    - via_servers
  tasks:
    - name: clean via
      file:
        path: "{{ deploy_dir }}/via"
        state: absent
      when: enable_deploy_via|default(false)

- hosts: consul
  tags:
    - consul_servers
  tasks:
    - name: clean consul
      file:
        path: "{{ deploy_dir }}/consul"
        state: absent
      when: enable_deploy_consul|default(false)

- hosts: carrier
  tags:
    - carrier_servers
  tasks:
    - name: clean carrier
      file:
        path: "{{ deploy_dir }}/carrier"
        state: absent
      when: enable_deploy_carrier|default(false)

- hosts: admin
  tags:
    - admin_servers
  tasks:
    - name: clean admin
      file:
        path: "{{ deploy_dir }}/admin"
        state: absent
      when: enable_deploy_admin|default(false)
    # 删除数据库
    - name: drop database
      shell: mysql -u{{ amin_user }} -p{{ admin_password }} -e "drop database if exists \`dev_metis_admin_0.3.0\`"
      register: result
      changed_when: false
      failed_when: result.rc != 0
      when: enable_deploy_admin|default(false)
    - name: Debug clean admin information
      debug:
        var: result.stdout
      when: enable_deploy_admin|default(false)

- hosts: data
  tags:
    - data_servers
  tasks:
    - name: clean data
      file:
        path: "{{ deploy_dir }}/data"
        state: absent
      when: enable_deploy_data|default(false)

- hosts: compute
  tags:
    - compute_servers
  tasks:
    - name: clean compute
      file:
        path: "{{ deploy_dir }}/compute"
        state: absent
      when: enable_deploy_compute|default(false)